services:

  db:
    image: postgresql
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hilal2418
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432